// <auto-generated />
using System;
using BadmintonParty.Liff.Web.Api.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BadmintonParty.Liff.Web.Api.Migrations
{
    [DbContext(typeof(BadmintonContext))]
    [Migration("20260616214915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.CourtEntity", b =>
                {
                    b.Property<string>("CourtId")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourtId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.GroupEntity", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.Property<int>("AlternatePeople")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConsumptionPatterns")
                        .HasColumnType("integer");

                    b.Property<string>("CourtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupStatus")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("integer");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinPeople")
                        .HasColumnType("integer");

                    b.Property<string>("OtherInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayTime")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId");

                    b.HasIndex("CourtId");

                    b.HasIndex("MemberId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.GroupMemberEntity", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.Property<string>("MemberId")
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.MemberEntity", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MemberId");

                    b.HasIndex("LineUserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.MemberRecentOpeningEntity", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("text");

                    b.Property<string>("CourtId")
                        .HasColumnType("text");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MemberId", "CourtId");

                    b.HasIndex("CourtId");

                    b.ToTable("MemberRecentOpenings");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.GroupEntity", b =>
                {
                    b.HasOne("BadmintonParty.Liff.Web.Api.Entities.CourtEntity", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonParty.Liff.Web.Api.Entities.MemberEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.GroupMemberEntity", b =>
                {
                    b.HasOne("BadmintonParty.Liff.Web.Api.Entities.GroupEntity", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonParty.Liff.Web.Api.Entities.MemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.MemberRecentOpeningEntity", b =>
                {
                    b.HasOne("BadmintonParty.Liff.Web.Api.Entities.CourtEntity", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BadmintonParty.Liff.Web.Api.Entities.MemberEntity", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BadmintonParty.Liff.Web.Api.Entities.GroupEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
